### PR TITLE
replace starting-ip-address to ip-addresses

### PR DESCRIPTION
**Pull request by bradyjoestar**
`starting-ip-address`  can't handle ip such as "172.172.0.1, 172.172.0.8".

### CODE REVIEW

**Review by chengwenxi — APPROVED** [review]

**Comment by chengwenxi** [comment]
golangci-lint shows that there are some unused code.

**Comment by bradyjoestar** [comment]
> golangci-lint shows that there are some unused code.

sure, I will fix it

**Review by wukongcheng — APPROVED** [review]

**Comment by chengwenxi** [comment]
The build workflow needs to be fixed.

**Comment by bradyjoestar** [comment]
> The build workflow needs to be fixed.

Get it.

**Pull request merged**
